jmdns/jmdns

- src/main/java/javax/jmdns/impl/DNSIncoming.java
RFC 6891 identifies the range of OPT codes from 65001 to 65534 as used
for experimental/local purposes. Receipt of answers containing these
OPT codes is not cause for alarm, and can be safely ignored. Reducing
logging of the receipt of these answers to FINE instead of WARNING.
Other unrecognized codes outside this range will continue to WARN.
Fixes #12
Signed-off-by: Andy Lintner <dev@beowulfe.com> (github: beowulfe)
> Reduced log level of experimental/local opt codes

- src/main/java/javax/jmdns/impl/DNSCache.java
Java 8 changed the signature of ConcurrentHashMap.keySet(), breaking compilation of javax.jmdns.impl.DNSCache. Considering that there are no consumers of this field within the project, and the class that contains it is in a impl package, removing it is the simplest option.
Fixes #15
Signed-off-by: Andy Lintner <dev@beowulfe.com> (github: beowulfe)
> Removed EmptyCache field from DNSCache

- src/main/java/javax/jmdns/impl/DNSOutgoing.java
- src/main/java/javax/jmdns/impl/DNSTaskStarter.java
- src/main/java/javax/jmdns/impl/JmDNSImpl.java
- src/main/java/javax/jmdns/impl/tasks/Responder.java
Request for Comments: 6762
(https://tools.ietf.org/html/rfc6762)
Multicast DNS
6.7.  Legacy Unicast Responses
If the source UDP port in a received Multicast DNS query is not port
5353, this indicates that the querier originating the query is a
simple resolver such as described in Section 5.1, "One-Shot Multicast
DNS Queries", which does not fully implement all of Multicast DNS.
In this case, the Multicast DNS responder MUST send a UDP response
directly back to the querier, via unicast, to the query packet's
source IP address and port.
Signed-off-by: Markus Rathgeb <maggu2810@gmail.com>
> support "Legacy Unicast Responses"

- src/main/java/javax/jmdns/impl/ServiceInfoImpl.java
- src/test/java/javax/jmdns/test/ServiceInfoTest.java
This commit fixes an issue with parsing TXT records without '=' in them.
The result of the issue is that the whole TXT record will be
considered invalid and the service will appear not have any properties
at all unless you use the raw byte array.
Signed-off-by: Mårten Borgström <martenborgstrom@gmail.com> (github: martenbr)
> Fixed handling of TXT records without '='

- build.xml
- src/main/java/javax/jmdns/impl/DNSCache.java
Two things are addressed here:
1) "ant jar" works again by removing duplicate classes and old tools. It's probably no longer used, but FWIW.
2) JmDNS toString() does not crash anymore after building with Java 8, something similar to #17.
Signed-off-by: Eric Chen <taiyang.chen@gmail.com> (github: taiyangc)
> Fix building issues

- src/main/java/javax/jmdns/impl/DNSRecord.java
- src/main/java/javax/jmdns/impl/JmDNSImpl.java
- src/main/java/javax/jmdns/impl/constants/DNSConstants.java
- src/test/java/javax/jmdns/test/DNSRecordTest.java
Signed-off-by: Carsten <carsten@meyermuc.de>
We'd like to conritubte an enhancement that we recently implemented because we encountered the following problem:
In our environment there a a lot of service instances (for the same service type, >30) and a lot of listeners for these service (> 20). Under certain circumstances we saw MDNS traffic on our network exceeding 1 MB/s (caused by our services).
Close investigation revealed the following:
Since some of service instances were sometimes not shutdown correctly (no "Goodbye"-Packets), these remained in the cache of all the listeners. During cache cleanup (every 10s) each listener would try to renew this service once the TTL of this record is less than 50% of its original value (60 min).
This leads to the following behaviour:
After 30 min, …
> Prevent unnecessary network traffic during cache cleanup, with test

- src/main/java/javax/jmdns/impl/NameRegister.java
Minor change, should be evident that wrong variable is used.
> Set checks if it contains itself. Fixed to check for name parameter.

- src/main/java/javax/jmdns/JmmDNS.java
This closes #49.
Signed-off-by: Cameron Gutman <aicommander@gmail.com> (github: cgutman)
> Fix a race that can cause JmmDNS.Factory.getInstance() to return a closing JmmDNS object

- src/main/java/javax/jmdns/impl/DNSQuestion.java
Since subtype name is not a Type, DNSQuestion.AllRecords.addAnswers()
API is not able to get a ServiceInfo instance and fails to answer the
query.
To fetch the ServiceInfo for the relevant SubType, we have to iterate all the registered ServiceInfo and provide the response for incoming request.
Tested with Bonjour Conformance Test tool. Was able to pass the test. 
Fixes #64 
Signed-off-by: Santhosh Kani santhosh.kani@gmail.com (github: SanthoshKani)
> JmDns not responding to sub-type T_ANY request

- pom.xml
type jar is default and must not be set
Signed-off-by: Stefan Eicher <stefan.eicher@gmail.com> (github: stefaneicher)
> type jar is default and must not be set

- README.md
Handy way to find the status of latest version deployed to Maven Central.
> Add Maven Central badge status to readme

- src/main/java/javax/jmdns/impl/JmDNSImpl.java
- src/main/java/javax/jmdns/impl/ListenerStatus.java
Signed-off-by: Victor Toni <victor.toni@gmail.com>
> Corrected spelling of ASYNCHONEOUS/SYNCHONEOUS.

- src/main/java/javax/jmdns/impl/ServiceInfoImpl.java
- src/test/java/javax/jmdns/test/TextUpdateTest.java
Fixes #99. This allows subtypes containing capital letters to be discoverable be services that depend on  them. 
Signed-off-by: Matt Becker matt.s.becker@gmail.com (github: mattsbecker)
> Removed .toLowerCase() on subtype return in getTypeWithSubtype

- src/main/java/javax/jmdns/impl/JmDNSImpl.java
Fixes #82
Previously, close() put JmDNSImpl into a CANCELING_1 state, which would transition to
CANCELING_2, CANCELING_3, and finally CANCELED.  close() waited the for CANCELED state,
which took about 2 seconds, during which time broadcasts are sent out to remove services
that were advertised.  In Jan 20, 2011 this was changed to put JmDNSImpl into a CLOSING
state, which would transition to CLOSED, but close() still waits for CANCELED, which no
longer happens resulting in a 5 second timeout.  I tried changing to wait for CLOSED,
but then the logic to remove advertised services no longer gets executed.  Reverting to
the orignal logic is safe, and fixes the bug.
Signed-off-by: Ed Tyrrill <etyrrill@gmail.com> (github: etyrrill)
> Revert close() logic to previous behavior

- src/main/java/javax/jmdns/impl/JmDNSImpl.java
Using a specific network interface avoids the multicast group being joined on all interfaces.
This change is also needed to avoid crashing on Android when AP mode is active.
> Use joinGroup() with specific network interface if available.

- .travis.yml
The JDK oraclejdk7 is not supported by Travis anymore. Solves https://github.com/jmdns/jmdns/issues/149.
For details see:
https://github.com/travis-ci/travis-ci/issues/7019
Signed-off-by: Victor Toni <victor.toni@gmail.com>
> Fixed failing Travis-CI build due to removal of oraclejdk7.

- src/main/java/javax/jmdns/impl/DNSRecord.java
- src/main/java/javax/jmdns/impl/JmDNSImpl.java
- src/main/java/javax/jmdns/impl/ServiceInfoImpl.java
- src/main/java/javax/jmdns/impl/constants/DNSConstants.java
1. Issue#95 Fix cache-flush to follow mdns specification (RFC 6762, section 10.2 Announcements to Flush Outdated Cache Entries)
2. Fix warnings for listener events 
After fixing the cache-flush, ListenerStatus frequently fires new warnings "Service Resolved called for an unresolved event: {}".  This is caused by concurrent modification of the ServiceInfo object.
> Bugfix Issue#95 stale ip address still reported + Fix warnings for listener events

- src/main/java/javax/jmdns/impl/util/ByteWrangler.java
> Ignore invalid field length instead of crashing

- src/main/java/javax/jmdns/impl/DNSIncoming.java
in case of closed jmdns，process call create function to get more _messageInputStream because of the old one exist
Signed-off-by: Zippo <zippozeng@qq.com>
> fix jmdns oom error

- src/main/java/javax/jmdns/impl/DNSOutgoing.java
Allow dots in instance names as per rfc 6763. According to rfc6763 instance names are allowed to contain any characters, including dots. They recommend escaping them if concatenating all the parts internally. 
See section 4.3:
”4.3.  Internal Handling of Names”
https://github.com/jmdns/jmdns/blob/master/devdocs/txt/rfc6763.txt
Also see this from avahi: 
“Notes on DNS Name Escaping”
https://code.woboq.org/qt5/include/avahi-compat-libdns_sd/dns_sd.h.html
The reason for this requested support is that the European ITxPT public transport standard is using an additional extra field in the instance containing the separator dot.
While the loop with the separate fields could use a string split with a regexp instead this pull request preserves the code flow as it currently stands.
Otherwise a …
> Allow escape of dot in instance name

- src/main/java/javax/jmdns/ServiceInfo.java
- src/main/java/javax/jmdns/impl/ServiceInfoImpl.java
Fix a couple of bugs that caused ServiceInfo.getServer() to
always return an empty string when processing a resolved Service.
- ServiceInfoImpl.clone() didn't include _server
- ServiceInfoImpl.hasData() failed to properly check for _server being set
> Fix bug causing getServer() to always be empty (#164)

- src/main/java/javax/jmdns/impl/DNSCache.java
- src/test/java/javax/jmdns/impl/DNSCacheTest.java
#205 - Fixing Android Desugaring issue by making DNSCache have an instance of ConcurrentHashMap instead of inheriting from it.
> #205 - Fixing Desugaring issue

- src/main/java/javax/jmdns/impl/JmmDNSImpl.java
Resolves #215
You can replace the JmDNS instance creation by subclassing JmmDnsImpl
```java
import java.io.IOException;
import java.net.InetAddress;
import javax.jmdns.JmDNS;
import javax.jmdns.impl.JmmDNSImpl;
public class FastJmmDnsImpl extends JmmDNSImpl
{
private static final String COMPUTER_NAME = System.getenv("COMPUTERNAME");
@Override
protected JmDNS createJmDnsInstance(InetAddress address) throws IOException
{
return JmDNS.create(address, COMPUTER_NAME);
}
}
```
and then passing this class as the JmmDNS ClassDelegate:
```java
JmmDNS.Factory.setClassDelegate(FastJmmDnsImpl::new);
```
> Allow overriding for JmDNS instance creation inside JmmDNSImpl

- src/main/java/javax/jmdns/impl/constants/DNSConstants.java
Fix #222
Allows configuration of mdns multicast group IP address by specifying them with the properties net.mdns.ipv4 and net.mdns.ipv6
> Make mdns group address configurable

- src/main/java/javax/jmdns/impl/JmmDNSImpl.java
On modern macOS versions, the `NetworkChecker` can take a long time to finish.
This lets the Timer perform the check in background immediately after invocation, instead of blocking the Initializers by calling `run()` directly.
> Always perform NetworkChecker task in background

- src/main/java/javax/jmdns/impl/ServiceInfoImpl.java
JmDNS instance invokes getServiceInfo,  but did not wait for enough time, then returned null value.  
When the ServiceInfo's updateRecord method was invoked, even if there is not any data change in this ServiceInfo,  It will notify all the threads which wait  at the ServiceInfo.  That's why the  wait method in waitForInfoData was awaken unexpected.
The correct behavior is:   The ServiceInfo will not notifyAll if there is not any data change.  If there is data change, the ServiceInfo will notify that it is changed.  Then the info.wait(200) in waitForInfoData will be notified.
> getServiceInfo returns null sometimes

- pom.xml
Version 1.7.25 is already 3 years old, and Synopsis Detect is giving operational risk on it.
> Taking the version of SLF4J-API to latest available at this moment.

- src/main/java/javax/jmdns/impl/DNSCache.java
- src/main/java/javax/jmdns/impl/ServiceInfoImpl.java
Use more accurate map implementations and presize the lists inside the 
cache to reduce the memory usage.
> Slightly reduced memory usage of the DNSCache

- .github/workflows/maven.yml
This is an initial drop of GitHub Actions to allow maven building/validation of push/pull directly on GitHub.
Note that `Dependency graph` must be enabled for the repository to allow the action to successfully build.
```
On GitHub.com, navigate to the main page of the repository.
Under your repository name, click
Settings. If you cannot see the "Settings" tab, select the
dropdown menu, then click Settings. Screenshot of a repository header showing the tabs. The "Settings" tab is highlighted by a dark orange outline.
In the "Security" section of the sidebar, click
Code security and analysis.
Read the message about granting GitHub read-only access to the repository data to enable the dependency graph, then next to "Dependency Graph", click Enable.
```
> Add actions for GitHub

- src/main/java/javax/jmdns/impl/ServiceTypeDecoder.java
- src/test/java/javax/jmdns/impl/ServiceTypeDecoderTest.java
Moving here fix from https://github.com/jmdns/jmdns/pull/253
`decodeQualifiedNameMapForType` was not able to parse correctly the A/AAA records because the published type is of the format `android_1234.local.`. This was breaking as the `_qualifiedNameMap` recognized the type as only application name due to the underscore in the instance name. Checking the RFC and browsing I came to the conclusion that A/AAA records can only be formatted as <instance>.<domain>. The fix adds an additional regex to support the A/AAA record type format. This solved the majority of the issues where the A/AAA record where stored in cache with the wrong key and never found.
Big problem I encountered and probably will create an issue here is that one of the behaviors changed, and so the test.
One of the tests …
> Improve support to atype service type

- src/main/java/javax/jmdns/impl/SocketListener.java
- src/main/java/javax/jmdns/impl/tasks/Responder.java
While setting up a printer discovery with jmdns, I found that QU queries are not sent back to the sender's ip address , but back to the broadcast address.
Fixes #153 
Fixes #221
> Send Answers to QU queries back to sender's address

- src/main/java/javax/jmdns/impl/DNSEntry.java
- src/main/java/javax/jmdns/impl/ServiceInfoImpl.java
This PR will use a `StringBuilder` in areas where a lot of temporary strings are created.
To lower the object fallout while handling DNS requests. 
Signed-off-by: Jörg Sautter <joerg.sautter@gmx.net>
> Create less temporary strings

- .classpath
- src/main/java/javax/jmdns/impl/DNSCache.java
- src/main/java/javax/jmdns/impl/DNSIncoming.java
- src/main/java/javax/jmdns/impl/util/SimpleLockManager.java
- src/test/java/javax/jmdns/test/DNSCacheTest.java
Hi
The changes are two address 2 issues
problems with door bell camera malformed records, see OOM and high CPU caused by door camera #186
concurrency issues in DNSCache
The problem has been reported here DNSCache leak #200
Fix is provided by Remove entries with no records (jmdns#200) #201 and included in 3.5.6.
Diff for the fix https://github.com/jmdns/jmdns/pull/201/files
It seems however that the fix is incomplete and will have other issues
concurrency issue on entryList.isEmpty() method
concurrency issue with record being added whilst entryList is removed at the same time
This change provides more coarse locking to solve above issues.
> Fix for OOM and concurrency issues in DNSCache 

- src/main/java/javax/jmdns/impl/DNSIncoming.java
- src/main/java/javax/jmdns/impl/DNSMessage.java
- src/main/java/javax/jmdns/impl/DNSOutgoing.java
- src/main/java/javax/jmdns/impl/constants/DNSRecordClass.java
- src/main/java/javax/jmdns/impl/constants/DNSRecordType.java
- src/test/java/javax/jmdns/test/DNSRecordTest.java
This PR is intended to fix the issue #282 
- _WARNING_ level log changed to  _DEBUG_ level in `DNSRecordClass.classForIndex()`
- _WARNING_ level log changed to  _DEBUG_ level in `DNSRecordType.typeForIndex()`
- Removed `InetAddress` parameter from `DNSIncoming.readAnswer()` to get unified usage of `_packet` field
- `DNSMessage` dump changed from _WARNING_ level to _DEBUG_ level. 
- Call `DNSIncoming.print(boolean dump)` only if debug level logging is enabled (further details: [java:S2629](https://rules.sonarsource.com/java/type/Code%20Smell/RSPEC-2629/)).
- Removed duplicate printouts of DNS entries from `DNSIncoming.print(boolean dump)`. Listing of _questions_, _answers_, _additionals_, etc. moved from `DNSIncoming.toString()` method to the `DNSMessage.print()` method of the base class. …
> Bring relief on excessive logging from DNSIncoming() class

- pom.xml
- src/main/java/javax/jmdns/impl/DNSIncoming.java
- src/test/java/javax/jmdns/impl/DNSRecordTest.java
Fixed failing DNSRecordTest.
cc @janossch
> Fix DNSRecordTest

- src/main/java/javax/jmdns/impl/DNSRecord.java
Fix #106: DNSRecord a few places not null checking getAddress()
`getAddress()` can be NULL and a couple of places were not NULL checking
> Add DNSRecord not null checks

- src/main/java/javax/jmdns/impl/DNSRecord.java
Fix #162: DNSRecord better address equality check
`Object.equals()` handles NULLS on both sides
> Fix #162: DNSRecord better address equality check

- src/main/java/javax/jmdns/impl/DNSRecord.java
Fix #194 
- Remove null check before calling StringBuilder.append() method.
https://github.com/jmdns/jmdns/blob/3499b05b21377c9f7db9de6cd5422d90c69c78c7/src/main/java/javax/jmdns/impl/DNSRecord.java#L570
> Fix superfluous null check in DNSRecord

- src/main/java/javax/jmdns/impl/tasks/DNSTask.java
- src/main/java/javax/jmdns/impl/tasks/Responder.java
- src/main/java/javax/jmdns/impl/tasks/resolver/DNSResolverTask.java
- src/main/java/javax/jmdns/impl/tasks/resolver/ServiceInfoResolver.java
- src/main/java/javax/jmdns/impl/tasks/resolver/ServiceResolver.java
- src/main/java/javax/jmdns/impl/tasks/state/DNSStateTask.java
- Remove unnecessary whitespaces
- fix several typos in comments, 
- rename local and field variables (remove leading "_")
- use `@throws` instead of `@exception` in comments
- change the `public` constructor of the `public abstract DNSResolverTask` class to `protected`
> Code cleanup in packages under javax.jmdns.impl.tasks.

- src/main/java/javax/jmdns/impl/ServiceInfoImpl.java
Fix #185: ServiceInfo keep property order
> Fix #185: ServiceInfo keep property order

- src/main/java/javax/jmdns/impl/DNSQuestion.java
Fix #259: DNSQuestion consistency to only add answers from matching service
Refactor to prevent duplicate code and check for  host match in both `Address` and `Server` consistently.
> DNSQuestion consistency to only add answers from matching service

- pom.xml
- src/test/java/javax/jmdns/impl/DNSCacheTest.java
- src/test/java/javax/jmdns/impl/DNSMessageTest.java
- src/test/java/javax/jmdns/impl/DNSRecordTest.java
- src/test/java/javax/jmdns/impl/JmDNSTest.java
- src/test/java/javax/jmdns/impl/ServiceInfoImplTest.java
- src/test/java/javax/jmdns/impl/ServiceTypeDecoderTest.java
- src/test/java/javax/jmdns/test/DNSStatefulObjectTest.java
- src/test/java/javax/jmdns/test/EventContainer.java
- src/test/java/javax/jmdns/test/EventStoringServiceListener.java
- src/test/java/javax/jmdns/test/JmmDNSTest.java
- src/test/java/javax/jmdns/test/ServiceInfoTest.java
- src/test/java/javax/jmdns/test/TextUpdateTest.java
- src/test/java/javax/jmdns/test/extensions/TestNameLogger.java
- src/test/java/javax/jmdns/test/util/ReflectionUtils.java
- src/test/java/javax/jmdns/test/util/StringUtil.java
- src/test/java/javax/jmdns/util/ByteWranglerTest.java
- src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
- src/test/resources/junit-platform.properties
I wanted to move the below listed files under `javax.jmdns.impl` package, but it needs to be a separate PR (even if they are moved, git cannot preserve their history).
- _DNSStatefulObjectTest.java_
- _JmmDNSTest.java_
- _ServiceInfoTest.java_
- _TextUpdateTest.java_
**No goal:**
- optimize on tests (performance)
- stabilize tests (I can not guarantee there aren't any `flaky` tests)
- remove duplicate tests
- since more or less all `JmDNS` and `JmmDNS` tests are multi-threaded, it was no goal to remove `Thread.sleep()`
> TEST ONLY - Improving tests

- pom.xml
Fixes #324
@ViToni  @kaikreuzer  @melloware 
With a parallel PR https://github.com/jmdns/jmdns/pull/318 I've introduced a _logback-classic_ dependency which is not compatible with JDK8 builds (similarly as _mockito_)
- Downgrade logback-classic test dependency to be compatible with JDK8
- Upgrade maven-compiler-plugin to 3.13.0 (more info about its [use under JDK8](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-release.html#usage-on-jdk-8) and see related [JEP](https://openjdk.org/jeps/247)).
> Downgrade logback-classic test dependency to be compatible with JDK8

- src/test/java/javax/jmdns/impl/DNSStatefulObjectTest.java
- src/test/java/javax/jmdns/impl/JmmDNSTest.java
- src/test/java/javax/jmdns/impl/ServiceInfoTest.java
- src/test/java/javax/jmdns/impl/TextUpdateTest.java
This is a continuation of https://github.com/jmdns/jmdns/pull/318. I couldn't move these files within the same PR.
> TEST_ONLY Move test classes under javax.jmdns.impl package.

- pom.xml
Setting the value to `JavaSE-8` (implicitly introduced in #326) seems to cause issues.
`JavaSE-1.8` works fine for openHAB project.
> Set minimum RequiredExecutionEnvironment to JavaSE-1.8
