- src/main/java/javax/jmdns/impl/DNSOutgoing.java
> fixes resource leaks from opened streams

- README.md
- pom.xml
- src/main/java/javax/jmdns/impl/JmDNSImpl.java
- src/test/java/javax/jmdns/test/JmDNSTest.java
> removed command line docu, deactivated tests on a default maven build

- pom.xml
> some further pom.xml cleanup

- src/main/java/javax/jmdns/impl/DNSRecord.java
> made sameValue more forgiving

- src/main/java/javax/jmdns/ServiceInfo.java
- src/main/java/javax/jmdns/impl/ListenerStatus.java
- src/main/java/javax/jmdns/impl/ServiceInfoImpl.java
Compare addresses when checking service info equality
> Fixes jmdns/jmdns#51

- pom.xml
- src/main/java/javax/jmdns/JmDNS.java
- src/main/resources/version.properties
This is a proposed fix for the issue [57](https://github.com/jmdns/jmdns/issues/57)
Signed-off-by: Carsten <carsten@meyermuc.de>
> read version from filtered resource file

- src/main/java/javax/jmdns/impl/HostInfo.java
https://github.com/jmdns/jmdns/issues/62
Signed-off-by: Dominik Hufnagel <d.hufi@gmx.de> (github: dhufnagel)
> Fixing hostname issue with IPv6 addresses

- src/main/java/javax/jmdns/impl/HostInfo.java
This patch fixes spelling errors in logger.
> Fixed typo in logger

- README.md
I have updated and fixed the examples. See #75
> Update & improve the examples.

- src/main/java/javax/jmdns/impl/JmDNSImpl.java
- src/main/java/javax/jmdns/impl/ListenerStatus.java
- src/test/java/javax/jmdns/impl/JmDNSTest.java
> Only allow a listener to be added once.

- lib/jmdns.manifest
delete unused file
Signed-off-by: Stefan Eicher <stefan.eicher@gmail.com> (github: stefaneicher)
> delete unused file jmdns.manifest

- src/main/java/javax/jmdns/impl/NetworkTopologyDiscoveryImpl.java
#69
Signed-off-by: Dominik Hufnagel <d.hufi@gmx.de> (github: dhufnagel)
> Fixing JmmDNS loopback interfaces binding issue

- src/main/java/javax/jmdns/impl/JmDNSImpl.java
Removing a System.out line that is probably forgotton while debuging
Signed-off-by: Miki Jankov <miki.jankov87@gmail.com>
> Removing a System.out line that is probably forgotton while debuging

- README.md
Just minor formatting changes that make it looks nicer.
* enabled syntax highlighting
* removed 1 indentation
> README code formatting

- src/main/java/javax/jmdns/impl/DNSCache.java
- src/main/java/javax/jmdns/impl/JmDNSImpl.java
- src/main/java/javax/jmdns/impl/ServiceInfoImpl.java
If a device loses its connection the device will not be removed until its PTR record expires (75min).
This PR will change this behaviour insofar that it removes the service when the last of its IP (v4/v6) has expired, means the device is no longer reachable.
> ServiceInfo of unreachable devices gets removed with expiration of IP address.

- src/main/java/javax/jmdns/ServiceInfo.java
- src/main/java/javax/jmdns/impl/DNSRecord.java
- src/main/java/javax/jmdns/impl/ServiceInfoImpl.java
- src/main/java/javax/jmdns/impl/util/ByteWrangler.java
- src/test/java/javax/jmdns/impl/ServiceInfoImplTest.java
- src/test/java/javax/jmdns/util/test/ByteWranglerTest.java
- src/test/java/util/StringUtil.java
The ServiceInfoImpl class contained lots of byte handling code which does belong core functionality / logic.
This code has been extracted into its own class.
The code moved has now tests attached so that further changes have a testing baseline.
> Centralize byte handling into ByteWrangler class and added byte handling tests.

- src/main/java/javax/jmdns/impl/util/ByteWrangler.java
The custom UTF-8 failed to parse emojis correctly. The custom functions were replaced with standard functions.
Fixes https://github.com/jmdns/jmdns/issues/151
> Replaced custom UTF-8 parsing with standard functions. (see #151 )

- src/main/java/javax/jmdns/impl/JmDNSImpl.java
Signed-off-by: Dominik Hufnagel d.hufi@gmx.de (github: dhufnagel)
> Added network interface to MulticastSocket (see #145)

- src/main/java/javax/jmdns/impl/DNSRecord.java
> Some bad services can trigger null text value

- pom.xml
> updated to slf4j 1.7.25

- .travis.yml
> switched to Java8 for the build

- src/main/java/javax/jmdns/impl/DNSCache.java
- src/test/java/javax/jmdns/test/DNSCacheTest.java
Signed-off-by: Edgar Sousa <edgar.sousa@tridonic.com> (edgsousa)
> Remove entries with no records (jmdns#200)

- pom.xml
> change distribution from Bintray to Maven Central

- src/main/java/javax/jmdns/impl/DNSOutgoing.java
> fix error in IDE due to visibility

- src/main/java/javax/jmdns/impl/DNSCache.java
- src/test/java/javax/jmdns/test/DNSCacheTest.java
This reverts commit 6d747fb5dd9d36fc781d6dac056881b10585ff9c.
Fixes https://github.com/jmdns/jmdns/issues/211
> Revert "Fixing desugaring issue"

- src/main/java/javax/jmdns/impl/DNSEntry.java
> Correctly convert UTF-8 String to bytes

- pom.xml
fix for https://github.com/jmdns/jmdns/issues/155
> Make jmdns compatible with Java 9 module system

- src/main/java/javax/jmdns/impl/DNSIncoming.java
This PR will collect the name inside a single `StringBuilder` and create the substrings at the end, instead of maintaining the substrings while reading each fragment of the name.
Signed-off-by: Jörg Sautter <joerg.sautter@gmx.net>
> Collect the name inside a single StringBuilder

- src/main/java/javax/jmdns/impl/DNSQuestion.java
- src/main/java/javax/jmdns/impl/ServiceInfoImpl.java
> Add check if subtype matches when answering a DNSQuestion

- src/main/java/javax/jmdns/impl/ServiceInfoImpl.java
Follow up from #268 , came from refactoring
> Fix bug in answers in ServiceImplInfo

- src/main/java/javax/jmdns/impl/DNSEntry.java
This is the fix to the issue #281 introduced in #275, sorry for breaking it.
Signed-off-by: Jörg Sautter <joerg.sautter@gmx.net>
> Fix #291 by removing the faulty domain prefix

- src/main/java/javax/jmdns/impl/util/ByteWrangler.java
- src/test/java/javax/jmdns/util/test/ByteWranglerTest.java
> ByteWrangler fixed unit tests and minor refactor

- src/main/java/javax/jmdns/impl/ServiceInfoImpl.java
Fix #245: ServiceIInfo defend against NPE's
> ServiceIInfo defend against NPEs

- src/main/java/javax/jmdns/impl/DNSCache.java
- src/main/java/javax/jmdns/impl/util/SimpleLockManager.java
Fix #186 
This is to based on discussions in the comments onwards
https://github.com/jmdns/jmdns/issues/186#issuecomment-2308543051
Related to potential lack of visibility of mutations in the entryLists between threads
> Fix issue with visibility of modification in DNSCache and docs cleanup in SimpleLockManager

- src/main/java/javax/jmdns/impl/HostInfo.java
Fix #70: Check for Host Name as well as address
> Fix #70: Check for Host Name as well as address

- .gitattributes
Fix #297 
Hide unwanted files from the language stats.
> Linguist configuration was added to .gitattributes

- pom.xml
> Fix mismatch of Mockito library / JDK version preventing test compilation

- .github/workflows/maven.yml
- pom.xml
on Mac OS
```
JmmDNSTest.testRegisterService:64 We should see the service we just registered:  ==> expected: <true> but was: <false>
[INFO] 
Error:  Tests run: 80, Failures: 5, Errors: 0, Skipped: 0
```
> Run tests on windows, mac, linux

- .github/workflows/maven.yml
- src/main/java/javax/jmdns/impl/DNSQuestion.java
Fix #333: Reduce logger WARN to DEBUG to reduce noise
> Fix #333: Reduce logger WARN to DEBUG to reduce noise

- src/main/java/javax/jmdns/JmmDNS.java
Closes #339
Signed-off-by: Zachary Peltzer <zachary.peltzer@zoetis.com> (github: ZacharyPeltzer-Zoetis)
> Check for `null` in `JmmDNS.Factory.close`

- src/main/java/javax/jmdns/impl/DNSEntry.java
- src/test/java/javax/jmdns/impl/DNSEntryTest.java
Replaces https://github.com/jmdns/jmdns/pull/342
> Fix Subtype PTR record TTL updates
